"""create fantasy data model tables

Revision ID: 4bdec88e6496
Revises: 88514573fd22
Create Date: 2026-07-12 16:14:39.943767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4bdec88e6496"
down_revision: Union[str, None] = "88514573fd22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "headshots",
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("player_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("platform", "player_id"),
    )
    op.create_table(
        "http_cache",
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("params_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("platform", "endpoint", "params_hash"),
    )
    op.create_table(
        "leagues",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("team_count", sa.Integer(), nullable=False),
        sa.Column("scoring_type", sa.String(length=32), nullable=False),
        sa.Column("current_week", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "live_nfl_games",
        sa.Column("nfl_game_id", sa.String(length=64), nullable=False),
        sa.Column("home_team", sa.String(length=8), nullable=False),
        sa.Column("away_team", sa.String(length=8), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("clock", sa.String(length=16), nullable=True),
        sa.Column("period", sa.Integer(), nullable=True),
        sa.Column("kickoff_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nfl_game_id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.String(length=8), nullable=False),
        sa.Column("nfl_team", sa.String(length=8), nullable=False),
        sa.Column("nfl_opponent", sa.String(length=8), nullable=True),
        sa.Column("nfl_game_id", sa.String(length=64), nullable=True),
        sa.Column("bye_week", sa.Integer(), nullable=True),
        sa.Column("injury_status", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_runs_job_name"), "refresh_runs", ["job_name"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("league_id", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("manager_name", sa.String(length=255), nullable=False),
        sa.Column("record_w", sa.Integer(), nullable=False),
        sa.Column("record_l", sa.Integer(), nullable=False),
        sa.Column("record_t", sa.Integer(), nullable=False),
        sa.Column("rank_current", sa.Integer(), nullable=False),
        sa.Column("rank_total", sa.Integer(), nullable=False),
        sa.Column("points_for", sa.Float(), nullable=False),
        sa.Column("points_against", sa.Float(), nullable=False),
        sa.Column("is_user_team", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_league_id"), "teams", ["league_id"], unique=False)
    op.create_table(
        "matchups",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("league_id", sa.String(length=255), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.String(length=255), nullable=False),
        sa.Column("away_team_id", sa.String(length=255), nullable=False),
        sa.Column("home_score", sa.Float(), nullable=False),
        sa.Column("away_score", sa.Float(), nullable=False),
        sa.Column("home_proj", sa.Float(), nullable=False),
        sa.Column("away_proj", sa.Float(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matchups_league_id"), "matchups", ["league_id"], unique=False)
    op.create_table(
        "roster_slots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.String(length=255), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("slot", sa.String(length=8), nullable=False),
        sa.Column("player_id", sa.String(length=255), nullable=False),
        sa.Column("proj_points", sa.Float(), nullable=False),
        sa.Column("actual_points", sa.Float(), nullable=False),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("game_state", sa.String(length=16), nullable=True),
        sa.Column("status_text", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "week", "slot", name="uq_roster_slots_team_week_slot"),
    )
    op.create_index("ix_roster_slots_team_week", "roster_slots", ["team_id", "week"], unique=False)
    op.create_table(
        "season_weeks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.String(length=255), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("opp_score", sa.Float(), nullable=False),
        sa.Column("opp_team_name", sa.String(length=255), nullable=False),
        sa.Column("is_win", sa.Boolean(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_season_weeks_team_week", "season_weeks", ["team_id", "week"], unique=True)
    op.create_table(
        "matchup_slots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("matchup_id", sa.String(length=255), nullable=False),
        sa.Column("slot", sa.String(length=8), nullable=False),
        sa.Column("home_player_id", sa.String(length=255), nullable=False),
        sa.Column("away_player_id", sa.String(length=255), nullable=False),
        sa.Column("home_pts", sa.Float(), nullable=False),
        sa.Column("away_pts", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matchup_id"],
            ["matchups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matchup_slots_matchup_id"), "matchup_slots", ["matchup_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matchup_slots_matchup_id"), table_name="matchup_slots")
    op.drop_table("matchup_slots")
    op.drop_index("ix_season_weeks_team_week", table_name="season_weeks")
    op.drop_table("season_weeks")
    op.drop_index("ix_roster_slots_team_week", table_name="roster_slots")
    op.drop_table("roster_slots")
    op.drop_index(op.f("ix_matchups_league_id"), table_name="matchups")
    op.drop_table("matchups")
    op.drop_index(op.f("ix_teams_league_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_refresh_runs_job_name"), table_name="refresh_runs")
    op.drop_table("refresh_runs")
    op.drop_table("players")
    op.drop_table("live_nfl_games")
    op.drop_table("leagues")
    op.drop_table("http_cache")
    op.drop_table("headshots")
    # ### end Alembic commands ###
